import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ee7ebb',
        'error-dim': '#a70138',
        'on-tertiary-fixed': '#360023',
        'on-secondary': '#f7f0ff',
        'primary': '#4b3fe2',
        'outline': '#757778',
        'surface-variant': '#dadddf',
        'tertiary-container': '#fe8bc9',
        'primary-fixed-dim': '#8985ff',
        'on-primary': '#f5f1ff',
        'on-primary-container': '#15007d',
        'secondary-dim': '#573ca4',
        'surface-bright': '#f5f6f7',
        'surface-container-low': '#eff1f2',
        'inverse-primary': '#8681ff',
        'on-secondary-fixed': '#3b1a88',
        'on-tertiary-fixed-variant': '#6d104d',
        'tertiary-fixed': '#fe8bc9',
        'inverse-on-surface': '#9b9d9e',
        'tertiary-dim': '#892a64',
        'on-primary-fixed': '#000000',
        'primary-fixed': '#9895ff',
        'surface-container-high': '#e0e3e4',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#510017',
        'on-secondary-container': '#4f329c',
        'on-error': '#ffefef',
        'surface-tint': '#4b3fe2',
        'secondary-fixed-dim': '#cbbaff',
        'on-surface-variant': '#595c5d',
        'primary-dim': '#3f2fd6',
        'on-primary-fixed-variant': '#1c0098',
        'secondary-container': '#d8caff',
        'error': '#b41340',
        'on-tertiary': '#ffeff4',
        'secondary': '#6348b1',
        'surface-dim': '#d1d5d7',
        'error-container': '#f74b6d',
        'inverse-surface': '#0c0f10',
        'on-surface': '#2c2f30',
        'on-tertiary-container': '#610243',
        'surface-container-highest': '#dadddf',
        'background': '#f5f6f7',
        'secondary-fixed': '#d8caff',
        'surface': '#f5f6f7',
        'on-background': '#2c2f30',
        'primary-container': '#9895ff',
        'tertiary': '#983771',
        'surface-container': '#e6e8ea',
        'outline-variant': '#abadae',
        'on-secondary-fixed-variant': '#583da6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
